openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for hello
paths:
    /hello/{name}:
        get:
            tags:
                - hello
            summary: say hello
            operationId: hello#say
            parameters:
                - name: name
                  in: path
                  description: name or message
                  required: true
                  schema:
                    type: string
                    description: name or message
                    example: Ullam sequi quidem qui in et excepturi.
                  example: Et ab soluta in.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: this is a result
                                example: Iste ratione voluptatum.
                            example: Aut officiis.
components: {}
tags:
    - name: hello
      description: The hello service says hello
