[540008link]
binance = "https://help.utrading.io/en/exchange/exchange-faq/how-to-change-binances-position-mode-to-hedge-mode"
bybit = "https://help.utrading.io/en/exchange/exchange-faq/how-to-change-bybits-position-mode-to-hedge-mode"
htx = "https://help.utrading.io/en/exchange/exchange-faq/how-to-change-the-one-way-mode-of-htx-to-hedge-mode"
